version: '3.8'
services:
  identity-service:
    build:
      context: ./identity-service
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/ajaxacademy
      - JWT_SECRET=super-secret-key
    depends_on:
      - mongo

  course-service:
    build:
      context: ./course-service
    ports:
      - '50020:5002'
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://mongo:27017/ajaxacademy
    depends_on:
      - mongo

  enrollment-service:
    build:
      context: ./enrollment-service
    ports:
      - '5003:5003'
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://mongo:27017/ajaxacademy
    depends_on:
      - mongo

  progress-service:
    build:
      context: ./progress-service
    ports:
      - '5004:5004'
    environment:
      - PORT=5004
      - MONGO_URI=mongodb://mongo:27017/ajaxacademy
    depends_on:
      - mongo

  notification-service:
    build:
      context: ./notification-service
    ports:
      - '5005:5005'
    environment:
      - PORT=5005
      - MONGO_URI=mongodb://mongo:27017/ajaxacademy
    depends_on:
      - mongo

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/ajaxacademy
    depends_on:
      - identity-service
      - course-service
      - enrollment-service
      - progress-service
      - notification-service
      - mongo

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ajaxacademy

volumes:
  mongo-data:
